[package]
name = "tzbuddy"
version = "0.2.0"
authors = ["Giacomo Bagnoli <gbagnoli@gmail.com>"]
edition = "2018"
homepage = "https://github.com/gbagnoli/tzbuddy.rs"
repository = "https://github.com/gbagnoli/tzbuddy.rs"
license-file = "LICENSE"
description = "tzbuddy simply diplays current date/time in several timezones, together with a few hours before and after"
readme = "README.md"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version= "3", features=["cargo", "derive"]}
chrono = "^0.4"
chrono-tz = "^0.6"
prettytable-rs = "^0.9"
